name: 'Upstream Sync'

on:
  schedule:
    - cron:  '*/5 * * * *'
    # scheduled for every 5 min

  workflow_dispatch:  # click the button on Github repo!

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo

    steps:
    # REQUIRED step
    # Step 1: run a standard checkout action, provided by github
    - name: Checkout target repo
      uses: actions/checkout@v3
      with:
        # optional: set the branch to checkout,
        # sync action checks out your 'target_sync_branch' anyway
        ref:  main
        # REQUIRED if your upstream repo is private (see wiki)
        persist-credentials: false

    # REQUIRED step
    # Step 2: run the sync action
    - name: Sync upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
      with:
        target_sync_branch: main
        # REQUIRED 'target_repo_token' exactly like this!
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_sync_branch: main
        # git_pull_args: --ff-only
        upstream_sync_repo: akashrajguru/fork-sync-upstream-action
        test_mode: false
      
    # Step 3: Display a message if 'sync' step had new commits (simple test)
    # - name: Check for new commits
    #   if: steps.sync.outputs.has_new_commits
    #   run: echo steps.sync.outputs.has_new_commits

    # # Step 4: Print a helpful timestamp for your records (not required, just nice)
    # - name: Timestamp
    #   run: date
    
    - name: Sync check
      if: failure()
      run: |
        echo "::error::Synchronization failed due to insufficient permissions (this is the expected behavior), please go to the warehouse homepage to execute manually[Sync fork]。"
        echo "::error::Due to insufficient permissions, synchronization failed (as expected). Please go to the repository homepage and manually perform [Sync fork]."
        exit 1
